### ISSUE TITLE
Add Data Structure and Algorithms Implementation 

### ISSUE THREAD

**Issue by aabhijeet011** [aabhijeet011/Data-Structure#1]
Contribute Either in same folders or creating new one. But code should be unique and well structured.

**Comment by Samikshahanchate** [comment]
Kindly assign me this issue , so I can contribute a clean DSA program in CPP language  for finding minimum and maximum element using divide and conquer method.

**Comment by aabhijeet011** [comment]
> Kindly assign me this issue , so I can contribute a clean DSA program in CPP language for finding minimum and maximum element using divide and conquer method.

sure , do it and make pull request.

**Comment by Shivamyana19** [comment]
hi , i have generated a pull request for adding a new sorting algorithm - count sort algorithm . Please merge it . Thank you. @aabhijeet011 
https://github.com/aabhijeet011/Data-Structure/pull/3

**Comment by Shivamyana19** [comment]
hii , @aabhijeet011  , i have created a pull request for Rat in a Maze probelm using Backtracking algorithm . Please merge it. Thanks.
https://github.com/aabhijeet011/Data-Structure/pull/6  Here is the PR.

**Comment by VaibhavM01** [comment]
hi ,I have  created a pull request  for adding new Searching Algorithm. please merge it.
